# Regras específicas para atividades acadêmicas FGV.
[required]
front_matter = ["ficha_tecnica"]
sections = ["introducao", "desenvolvimento", "consideracoes_finais", "referencias"]

[activity]
ficha_tecnica_unnumbered = true

[bibliography]
sistema_citacao = "autor-data"
referencias_ordenacao = "alfabetica"
notas_referencia = false
